version: '3.6'
services:
  # Init container to fix permissions
  init-permissions:
    image: alpine:latest
    volumes:
      - ./dur:/dur
    command: >
      sh -c "
        echo 'Fixing /dur directory permissions...' &&
        chown -R 51773:51773 /dur &&
        echo 'Permissions fixed successfully'
      "
    
  iris:
    depends_on:
      - init-permissions
    build: 
      context: .
      dockerfile: Dockerfile
    image: formation-fhir-python-iris:latest
    restart: always
    ports: 
      - 1972
      - 8089:52773
      - 53773
    volumes:
      - .:/irisdev/app
      - ./dur:/dur
    environment:
      - ISC_CPF_MERGE_FILE=/irisdev/app/merge.cpf
      - ISC_DATA_DIRECTORY=/dur/iris

  webgateway:
    image: containers.intersystems.com/intersystems/webgateway:latest-em
    init: true
    ports:
    - 443:443
    environment:
    - ISC_CSP_CONF_FILE=/webgateway/CSP.conf
    - ISC_CSP_INI_FILE=/webgateway/CSP.ini
    volumes:
      - ./webgateway:/webgateway
      - ./webgateway/cert:/opt/cert


  # postgres:
  #   image: postgres:13.2
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: ${POSTGRESQL_DB:-'keycloak'}
  #     POSTGRES_USER: ${POSTGRESQL_USER:-'keycloak'}
  #     POSTGRES_PASSWORD: ${POSTGRESQL_PASS:-'keycloak'}

  # keycloak:
  #   depends_on:
  #     - postgres
  #   environment:
  #     DB_VENDOR: postgres
  #     DB_ADDR: postgres
  #     DB_DATABASE: ${POSTGRESQL_DB:-'keycloak'}
  #     DB_USER: ${POSTGRESQL_USER:-'keycloak'}
  #     DB_PASSWORD: ${POSTGRESQL_PASS:-'keycloak'}
  #     KEYCLOAK_USER: ${KEYCLOAK_USER:-'admin'}
  #     KEYCLOAK_PASSWORD: ${KEYCLOAK_PASS:-'admin'}
  #     KEYCLOAK_HTTP_PORT: 8080
  #     KEYCLOAK_HTTPS_PORT: 8443
  #   volumes:
  #     - ./certificates/:/etc/x509/https
  #   image: jboss/keycloak:latest
  #   ports:
  #     - "8080:8080"
  #     - "8443:8443"
  #   restart: unless-stopped