POST https://localhost/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Vkbnrt9pQQMyU3UtKNdcKYC98FdFu9LC9dlVC5FIj4o:ydN3O8lBocYCN8AIcMKUrpbeH7sA9b9J4L2CVdNXGWhva8JpG2VX44lCom5RqOQVcvKwOeA7MeGPReLeb-V-ZA

grant_type=client_credentials&scope=user/*.* VIP&aud=https://webgateway/fhir/r4

###

GET https://webgateway/fhir/Patient?name=Michal
Content-Type: application/fhir+json
Accept: application/fhir+json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjEifQ.eyJqdGkiOiJodHRwczovL3dlYmdhdGV3YXkvb2F1dGgyLlZaZUdLMVVza3VZa2Q5ekxobnJqdHJSdXBTbyIsImlzcyI6Imh0dHBzOi8vd2ViZ2F0ZXdheS9vYXV0aDIiLCJzdWIiOiJWa2JucnQ5cFFRTXlVM1V0S05kY0tZQzk4RmRGdTlMQzlkbFZDNUZJajRvIiwiZXhwIjoxNzU2OTc3MTkzLCJhdWQiOiJodHRwczovL3dlYmdhdGV3YXkvZmhpci9yNCIsInNjb3BlIjoiVklQIHVzZXIvKi4qIiwiaWF0IjoxNzU2OTc2ODkzfQ.ehCSMfVoxQ5Egg8ZLi_hjSiAH7KgfCN28eXWaAYbwJQuYPXQW8QQ56BVBHl7l4XHDfgpWQZ43t2D4XPCBjmMvsG3eXQ93jy0gFgA_H4E4S3Pt-I_uLWBBgop_kCiIzdNnBVNYmRz-S5rbAk8qqIzS4et3ZahOmf_cGDzMlqJKwnwCOk1AB7RpNIkvG1xtUQmCPwgnplV3i2WNT2lhx_PNE9WoTn2D4oSsCm9LFA30xVNaGMiLGyeKCtpk_uvHWFvrmnHJ4xisb7l57Z9Kt_vxD7mItWDV4RUA2f56kedXAIMjKde1nwb_XB7al-flJoHfesvCm5If-Jj4pqmVf7FWg

###
POST https://localhost:4443/fhir/Patient 
Content-Type: application/fhir+json
Accept: application/fhir+json
prefer: return=representation
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6MX0.eyJqdGkiOiJodHRwczovL3dlYmdhdGV3YXkvb2F1dGgyLlo4ZU5zT0ZIYTVsalFOWm04T08zNXlJVlhRdyIsImlzcyI6Imh0dHBzOi8vd2ViZ2F0ZXdheS9vYXV0aDIiLCJzdWIiOiJ4dGM2NXJ1bVRtMjdnM0lxRmhhUWQxSGFDYndGYl9NbVM2aUZMSWR6UnFJIiwiZXhwIjoxNzA5NzIzMDI1LCJhdWQiOiJodHRwczovL3dlYmdhdGV3YXkvZmhpci9yNSIsInNjb3BlIjoidXNlci8qLioiLCJpYXQiOjE3MDk3MTk0MjV9.akq9-1-P9lDcVzlUBU4allVSI2i3nl0V2BcikdqNlqBn22He6jZnpIHb9y2gsWgQoeXWfvkNtBkb8CIDwap-5j68w12VYeiq_7uMTM7ni3h69iKWZLor8qFyQc2-4Y1cetVSC0X1ADAs25TL6JbEfFuMqKSMpuhwpUxXFaLOmYHovmBUgKmI2kedPQrUL3eVXWO_WpT4JcEUy0R3JkSTOpUM6FrvACrVNmTLje3LsEPlfuncCt0f4-S89TlzNsr_BqkMUSSfb8Fni0O6peiX38TcOBKqq_hzFAFhNoY5zH9Xp_xkB-dnTosymEQMLDl1ag89scvL6ZdyQRPqfzWlnw

{
    "resourceType": "Patient",
    "address": [
        {
            "city": "Lynnfield",
            "line": [
                "672 Bartoletti Arcade"
            ],
            "postalCode": "01940",
            "state": "Massachusetts"
        }
    ],
    "birthDate": "1994-08-02",
    "extension": [
        {
            "url": "http://intersystems.com/fhir/extn/sda3/lib/patient-entered-on",
            "valueDateTime": "2020-09-01T07:29:14+00:00"
        },
        {
            "url": "http://intersystems.com/fhir/extn/sda3/lib/patient-ethnic-group",
            "valueCodeableConcept": {
                "coding": [
                    {
                        "code": "2186-5",
                        "display": "non-hispanic",
                        "system": "urn:oid:2.16.840.1.113883.6.238"
                    }
                ]
            }
        },
        {
            "url": "http://intersystems.com/fhir/extn/sda3/lib/patient-races",
            "valueCodeableConcept": {
                "coding": [
                    {
                        "code": "2106-3",
                        "display": "white",
                        "system": "urn:oid:2.16.840.1.113883.6.238"
                    }
                ]
            }
        }
    ],
    "gender": "male",
    "identifier": [
        {
            "type": {
                "coding": [
                    {
                        "code": "MR",
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203"
                    }
                ],
                "text": "MRN"
            },
            "value": "26504347-0230-8fa0-a625-db55483a3d2d"
        }
    ],
    "name": [
        {
            "family": "Gaylord",
            "given": [
                "Michal"
            ],
            "text": "Michal Gaylord",
            "use": "official"
        }
    ],
    "id": "1",
    "meta": {
        "lastUpdated": "2024-02-24T09:11:00Z",
        "versionId": "1"
    }
}


###
GET https://localhost:4443/fhir/Patient/1/$diff
Content-Type: application/fhir+json
Accept: application/fhir+json
prefer: return=representation
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6MX0.eyJqdGkiOiJodHRwczovL3dlYmdhdGV3YXkvb2F1dGgyLkQwLTlGb2NCMUFkSzlzQ2NHbTdNRTJfSS1BMCIsImlzcyI6Imh0dHBzOi8vd2ViZ2F0ZXdheS9vYXV0aDIiLCJzdWIiOiJ4dGM2NXJ1bVRtMjdnM0lxRmhhUWQxSGFDYndGYl9NbVM2aUZMSWR6UnFJIiwiZXhwIjoxNzA5NzM5Mzc1LCJhdWQiOiJodHRwczovL3dlYmdhdGV3YXkvZmhpci9yNSIsInNjb3BlIjoiVklQIHVzZXIvKi4qIiwiaWF0IjoxNzA5NzM1Nzc1fQ.FwuDCDy8TE1p53fEzZljyhBuhhrP74lJ5sM05CBUTO0xjWHkuJTB0ndfr7bkxPg_Z_6DkzatE6DldbzRAqe25qRV_XIXlJzFkC20KD0slNrf6X627ejUvOpg7K20ju-KS9WDPwj3WEqIoqariAf_DLW9bFuq-u3YnLouOq1Cvtwk1v4uFt66pnOPxdIclK3j3dN6qIIume-Ei7qRweUzdtvilBD75dclQvQLxuu5uKeaAnkcVo4mCYjza36CqqiMPOIt4XsS5Msm9F3obm3xHzxCPHpkFqtdynh8MQLmzdvtz429ir11vHN9dLcStCh1wYYRZlF0Np6hTV4uYbc17w

{
    "resourceType": "Patient",
    "address": [
        {
            "city": "fdsf",
            "line": [
                "672 Bartoletti Arcade"
            ],
            "postalCode": "01940",
            "state": "Massachusetts"
        }
    ],
    "birthDate": "1994-08-02",
    "extension": [
        {
            "url": "http://intersystems.com/fhir/extn/sda3/lib/patient-entered-on",
            "valueDateTime": "2020-09-01T07:29:14+00:00"
        },
        {
            "url": "http://intersystems.com/fhir/extn/sda3/lib/patient-ethnic-group",
            "valueCodeableConcept": {
                "coding": [
                    {
                        "code": "2186-5",
                        "display": "non-hispanic",
                        "system": "urn:oid:2.16.840.1.113883.6.238"
                    }
                ]
            }
        },
        {
            "url": "http://intersystems.com/fhir/extn/sda3/lib/patient-races",
            "valueCodeableConcept": {
                "coding": [
                    {
                        "code": "2106-3",
                        "display": "white",
                        "system": "urn:oid:2.16.840.1.113883.6.238"
                    }
                ]
            }
        }
    ],
    "gender": "male",
    "identifier": [
        {
            "type": {
                "coding": [
                    {
                        "code": "MR",
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203"
                    }
                ],
                "text": "MRN"
            },
            "value": "26504347-0230-8fa0-a625-db55483a3d2d"
        }
    ],
    "name": [
        {
            "family": "Gaylord",
            "given": [
                "Michal"
            ],
            "text": "Michal Gaylord",
            "use": "official"
        }
    ],
    "id": "1",
    "meta": {
        "lastUpdated": "2024-02-24T09:11:00Z",
        "versionId": "1"
    }
}